import './ui/globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Header from './components/header';
import HeaderMobile from './components/header-mobile';
import MarginWidthWrapper from './components/margin-width-wrapper';
import PageWrapper from './components/page-wrapper';
import SideNav from './components/side-nav';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Side Nav w/ submenus',
  description: 'Generated by create next app',
};

export default function RootLayout({children,}: {children: React.ReactNode;}) 
{
  return (
    <html lang="en">
      <body className={`bg-white${inter.className}`}>
        {children}
        {/* <div className="flex">
          <SideNav />
          <main className="flex-1">
            <MarginWidthWrapper>
              <Header />
              <HeaderMobile />
              <PageWrapper>{children}</PageWrapper>
            </MarginWidthWrapper>
          </main>
        </div> */}
      </body>
    </html>
  );
}



// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }
